### PR TITLE
Orc: modifications to support a static build

### PR DESCRIPTION
**Pull request by capveg**
Reviewer: @rlane @jnealtowns

### CODE REVIEW

**Comment by rlane** [comment]
Need to resolve merge conflicts.

**Comment by rlane** [comment]
Otherwise LGTM.

**Comment by capveg** [comment]
ACK

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  Log file at http://vbs21/abat/2015.04.13.2039-m.bigcode.master/abat.log

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
Log file at http://vbs21/abat/2015.04.13.2039-m.bigcode.master/abat.log
/cc @rlane @jnealtowns

**Pull request merged**
