### PR TITLE
OF-DPA ORC driver

### PR DESCRIPTION
**Pull request by rizard**
@capveg 

Working on an OF-DPA driver for ORC. Does not compile and has not been tested -- this commit is just for documentation purposes and for potential feedback.

I'm still actively working on it and will make other commits in the near future as I progress.

### CODE REVIEW

**Comment by bsn-abat** [comment]
ABAT: AUTO-REJECT:  no reviewer specified in pull request description


INSTRUCTIONS: Please fix your problem by

1) Make sure line below is included in pull request description (not a follow-up comment):
Reviewer: @exampleuser1 @exampleuser2 @exampleuser3 ...
Leave no space at beginning of line. Use real GitHub IDs as reviewers.

2) Have at least one approval in any follow-up comment. An approval is given by including a single word of "ACK" (without quotes) in a line by itself. The approval can come from any person except the requester.

Under certain situations the requester can approve his/her own change. To do that, just include a single word of "SELF-ACK" (without quotes) in a line by itself. You are trusted not to abuse it :)

Any code review approval or new comment including the magic line of "R_E_T_R_Y" (Remove the underscores) will cause abat to automatically try to merge your code again.

**Comment by capveg** [comment]
@rizard : is this code ready for review or do you want more time with it?

**Comment by rizard** [comment]
@capveg I just pushed another round of updates. Adding and removing an interface works now. 

I need to handle a route with a kernel next hop correctly -- working on it now. The driver ignores that next hop now, but it should insert flows into the unicast routing and policy ACL tables to direct all packets to the kernel. 

I assume this kernel next hop in the route will be updated with the real next hop's MAC after the kernel learns the next hop MAC through ARP.

**Comment by rizard** [comment]
@capveg Feel free to take a look and let me know if there's anything obvious I need to rework. I haven't condensed anything yet, so there is repetition in places that I'll form into functions.

Adding and removing interfaces, routes, and next hops appears to be working (by observation of flow and group tables before/after ifconfig and route operations). I need to run now, but I'll try and test out with a real "next hop" using wiremonkey to check if the kernel next hop flows are indeed replaced with real next hop flows.

**Pull request closed without merging**
