### PR TITLE
IPv6 and ICMPv6 header parsing

### PR DESCRIPTION
**Pull request by adanivas**
Reviewer: @jnealtowns 

-Changes for IPV6 header and ICMPv6 header parsing
-Calculation of ICMPv6 checksum

### CODE REVIEW

**Comment by jnealtowns** [comment]
@adanivas Please resubmit after resolve conflicts.

**Comment by adanivas** [comment]
@jnealtowns Done. Resolved the conflicts.

**Comment by jnealtowns** [comment]
ACK

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  Log file at http://vbs25.eng.bigswitch.com/abat/2016.07.01.1633-m.bigcode.master/abat.log

**Comment by bsn-abat** [comment]
ABAT: AUTO-REJECT:  Your change failed pre-merge validation defined in bigcode/.abat-automerge. See log for details.


INSTRUCTIONS: Please fix your problem by

1) Reviewing the logs below and `git commit`ing a fix.

2) Use `git push` to add new commits to this same remote branch/pull request.

3) Get another code review approval from your co-worker indicated by a line of "ACK" in comment, or add another comment yourself with a line of "R_E_T_R_Y (Remove the underscores)". That will cause abat to try to merge your code again.



Log file at http://vbs25.eng.bigswitch.com/abat/2016.07.01.1633-m.bigcode.master/abat.log
/cc @rlane @jnealtowns

**Comment by adanivas** [comment]
RETRY

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  Log file at http://vbs26.eng.bigswitch.com/abat/2016.07.01.1855-m.bigcode.master/abat.log

**Comment by bsn-abat** [comment]
ABAT: AUTO-REJECT:  Your change failed pre-merge validation defined in bigcode/.abat-automerge. See log for details.


INSTRUCTIONS: Please fix your problem by

1) Reviewing the logs below and `git commit`ing a fix.

2) Use `git push` to add new commits to this same remote branch/pull request.

3) Get another code review approval from your co-worker indicated by a line of "ACK" in comment, or add another comment yourself with a line of "R_E_T_R_Y (Remove the underscores)". That will cause abat to try to merge your code again.



Log file at http://vbs26.eng.bigswitch.com/abat/2016.07.01.1855-m.bigcode.master/abat.log
/cc @rlane @jnealtowns

**Comment by adanivas** [comment]
RETRY

**Comment by adanivas** [comment]
RETRY

**Comment by adanivas** [comment]
RETRY

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
Log file at http://vbs25.eng.bigswitch.com/abat/2016.07.05.2058-m.bigcode.master/abat.log
/cc @rlane @jnealtowns

**Pull request merged**
