### PR TITLE
remove autogenerated makefiles and add gitignores

### PR DESCRIPTION
**Pull request by rlane**
Reviewer: trivial

### CODE REVIEW

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  Log file at http://vbs26.eng.bigswitch.com/abat/2016.04.01.1712-m.bigcode.master/abat.log

**Comment by bsn-abat** [comment]
ABAT: AUTO-REJECT:  Your change failed pre-merge validation defined in bigcode/.abat-automerge. See log for details.


INSTRUCTIONS: Please fix your problem by

1) Reviewing the logs below and `git commit`ing a fix.

2) Use `git push` to add new commits to this same remote branch/pull request.

3) Get another code review approval from your co-worker indicated by a line of "ACK" in comment, or add another comment yourself with a line of "R_E_T_R_Y (Remove the underscores)". That will cause abat to try to merge your code again.



Log file at http://vbs26.eng.bigswitch.com/abat/2016.04.01.1712-m.bigcode.master/abat.log
/cc @rlane @jnealtowns

**Comment by rlane** [comment]
VPI unit test failure:

```
04-01 10:20:33.023476 [vpi] (pcap|vpi-veth0)pcap_next_ex() failed: rv=0 err=
04-01 10:20:33.023712 [vpi] recv() returned -1: Inappropriate ioctl for device
```

**Comment by rlane** [comment]
RETRY

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  Log file at http://vbs24.eng.bigswitch.com/abat/2016.04.01.2332-m.bigcode.master/abat.log

**Comment by bsn-abat** [comment]
ABAT: ACCEPT:  Successfully merged

In case you want to see the build log, check out :
Log file at http://vbs24.eng.bigswitch.com/abat/2016.04.01.2332-m.bigcode.master/abat.log
/cc @rlane @jnealtowns

**Pull request merged**
