### PR TITLE
Adding support for 100G_AOC_LBER and 100G_ACC_LBER

### PR DESCRIPTION
**Pull request by ashutoshshanker22**

### CODE REVIEW

**Comment by ashutoshshanker22** [comment]
@jnealtowns / @archerhungbsn : Can you please review the changes and merge if it looks good to you? Thank you for your time and consideration.

**Comment by archerhungbsn** [comment]
@zhouzi88 Add Zi

**Comment by ashutosh-arrcus** [comment]
@jnealtowns / @archerhungbsn / @zhouzi88 : Please refer to SFF-8024 (Table 4-4 Extended Specification Compliance Codes) and SFF-8636 for further details.

**Comment by ashutoshshanker22** [comment]
@jnealtowns / @archerhungbsn / @zhouzi88 : Please refer to SFF-8024 (Table 4-4 Extended Specification Compliance Codes) and SFF-8636 for further details.

**Comment by ashutoshshanker22** [comment]
@jnealtowns / @archerhungbsn / @zhouzi88 : Is it possible to get this review done sooner and merge if it looks good? I really appreciate your help with this. Thank you for your time and consideration.

**Comment by jnealtowns** [comment]
@ashutoshshanker22 You will need to add the new types to https://github.com/floodlight/bigcode/blob/master/modules/sff/module/auto/sff.yml

Your changes will be lost the next time we run the autogenerator. 
Please add the new types to the yaml file and then run "make autogen" in the SFF module directory.

**Comment by ashutoshshanker22** [comment]
> @ashutoshshanker22 You will need to add the new types to https://github.com/floodlight/bigcode/blob/master/modules/sff/module/auto/sff.yml
> 
> Your changes will be lost the next time we run the autogenerator.
> Please add the new types to the yaml file and then run "make autogen" in the SFF module directory.

Thank you @jnealtowns . I will do it right away.

**Comment by ashutoshshanker22** [comment]
@jnealtowns : As per your suggestion I have added 100G-AOC-LBER and 100G-ACC-LBER to sff.yml for autogeneration. Thank you!

**Comment by ashutoshshanker22** [comment]
> @jnealtowns : As per your suggestion I have added 100G-AOC-LBER and 100G-ACC-LBER to sff.yml for autogeneration. Please let me know if it looks good to you. Thank you!

**Comment by ghost** [comment]
@jnealtowns : Thank you very much!

**Pull request merged**
