### PR TITLE
PPE: fix uninitialized variable warning at -O3

### PR DESCRIPTION
**Pull request by rlane**
Reviewer: trivial

### CODE REVIEW

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  Log file at http://vbs23.eng.bigswitch.com/abat/2015.10.17.0123-m.bigcode.master/abat.log

**Comment by bsn-abat** [comment]
ABAT: AUTO-REJECT:  Your change failed pre-merge validation defined in bigcode/.abat-automerge. See log for details.


INSTRUCTIONS: Please fix your problem by

1) Reviewing the logs below and `git commit`ing a fix.

2) Use `git push` to add new commits to this same remote branch/pull request.

3) Get another code review approval from your co-worker indicated by a line of "ACK" in comment, or add another comment yourself with a line of "R_E_T_R_Y (Remove the underscores)". That will cause abat to try to merge your code again.



Log file at http://vbs23.eng.bigswitch.com/abat/2015.10.17.0123-m.bigcode.master/abat.log
/cc @rlane @jnealtowns

**Comment by rlane** [comment]
@wilmo119 We need libedit-dev on the build servers.

**Comment by wilmo119** [comment]
RETRY

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  Log file at http://vbs23.eng.bigswitch.com/abat/2015.10.20.0619-m.bigcode.master/abat.log

**Comment by bsn-abat** [comment]
ABAT: AUTO-REJECT:  Your change failed pre-merge validation defined in bigcode/.abat-automerge. See log for details.


INSTRUCTIONS: Please fix your problem by

1) Reviewing the logs below and `git commit`ing a fix.

2) Use `git push` to add new commits to this same remote branch/pull request.

3) Get another code review approval from your co-worker indicated by a line of "ACK" in comment, or add another comment yourself with a line of "R_E_T_R_Y (Remove the underscores)". That will cause abat to try to merge your code again.



Log file at http://vbs23.eng.bigswitch.com/abat/2015.10.20.0619-m.bigcode.master/abat.log
/cc @rlane @jnealtowns

**Comment by wilmo119** [comment]
RETRY

**Comment by bsn-abat** [comment]
ABAT: START_MERGE:  Log file at http://vbs25.eng.bigswitch.com/abat/2015.10.19.2234-m.bigcode.master/abat.log

**Comment by bsn-abat** [comment]
ABAT: AUTO-REJECT:  Your change failed pre-merge validation defined in bigcode/.abat-automerge. See log for details.


INSTRUCTIONS: Please fix your problem by

1) Reviewing the logs below and `git commit`ing a fix.

2) Use `git push` to add new commits to this same remote branch/pull request.

3) Get another code review approval from your co-worker indicated by a line of "ACK" in comment, or add another comment yourself with a line of "R_E_T_R_Y (Remove the underscores)". That will cause abat to try to merge your code again.



Log file at http://vbs25.eng.bigswitch.com/abat/2015.10.19.2234-m.bigcode.master/abat.log
/cc @rlane @jnealtowns

**Pull request merged**
